"""BE-08 capabilities and limits contract tests.

Locks the ``app.routers.capabilities`` contract (execution-matrix.md BE-08
row; plan:675-679; arch 6.2; DEC-165): the typed canonical per-tool registry
carrying the R-03-approved table verbatim (gate-entry.md section 2), the
versioned ``GET /api/v1/capabilities`` endpoint (cacheable, deterministic,
immutable), the closed machine-readable failure-code vocabulary with
message keys from the existing envelope vocabulary (``app/errors.py``),
the deterministic mapping from BE-02 ``ValidationFailure`` categories to
failure codes ("a violating upload returns the matching machine-readable
code"), OpenAPI-schema determinism and privacy, and the ownership boundary
(the router is mounted in ``app/main.py`` by the single integration owner,
BE-09 wiring wave).

Fixture generation mirrors ``test_validation.py``: valid PDFs/images are
crafted in-test with pikepdf (pinned runtime dependency) and Pillow; a
1001-page PDF is generated by page replication (0.03 s) to exercise the
approved 1000-page cap; oversized images reuse the registry limit with
zero padding so the size gate fires before any decode.
"""

from __future__ import annotations

import dataclasses
import io
import json

import pikepdf
import pytest
from fastapi import FastAPI
from fastapi.routing import APIRoute
from fastapi.testclient import TestClient
from PIL import Image
from pydantic import ValidationError

from app.config import (
    DEFAULT_MAX_CONCURRENT_PER_ORIGIN,
    DEFAULT_MAX_QUEUE_LENGTH,
    DEFAULT_MAX_WAIT_SECONDS,
    DEFAULT_RETENTION_SECONDS,
    DEFAULT_TIMEOUT_SECONDS,
    Settings,
)
from app.main import create_app
from app.routers.capabilities import (
    CACHE_CONTROL,
    CONTRACT_VERSION,
    FAILURE_CODES,
    GLOBAL_LIMITS,
    TOOL_LIMITS,
    CapabilitiesResponse,
    FailureCode,
    FailureCodeEntry,
    FailureCodeMeta,
    GlobalLimits,
    ToolId,
    ToolLimits,
    capabilities_payload,
    failure_code_for,
    failure_code_meta,
    router,
)
from app.security.validation import (
    DEFAULT_MAX_IMAGE_PIXELS,
    DEFAULT_MAX_IMAGE_SIZE_BYTES,
    DEFAULT_MAX_PDF_PAGES,
    DEFAULT_MAX_PDF_SIZE_BYTES,
    ValidationFailure,
    ValidationRejection,
    validate_image,
    validate_pdf,
)

# --- approved R-03 reference payloads (gate-entry.md section 2, verbatim) ---

COMPRESS_PDF_LIMITS = {
    "maxFiles": 1,
    "maxFileBytes": 104_857_600,
    "maxTotalBytes": 104_857_600,
    "maxPages": 1000,
    "maxOutputs": 1,
    "maxPixelsPerImage": None,
    "maxPixelsPerPage": None,
    "maxTotalPixels": None,
    "maxEstimatedMemoryBytes": 1_610_612_736,
    "maxExecutionSeconds": 180,
    "maxZipBytes": None,
    "maxResultBytes": 536_870_912,
}

MERGE_PDF_LIMITS = {
    "maxFiles": 20,
    "maxFileBytes": 104_857_600,
    "maxTotalBytes": 209_715_200,
    "maxPages": 1000,
    "maxOutputs": 1,
    "maxPixelsPerImage": None,
    "maxPixelsPerPage": None,
    "maxTotalPixels": None,
    "maxEstimatedMemoryBytes": 1_610_612_736,
    "maxExecutionSeconds": 180,
    "maxZipBytes": None,
    "maxResultBytes": 536_870_912,
}

SPLIT_PDF_LIMITS = {
    "maxFiles": 1,
    "maxFileBytes": 104_857_600,
    "maxTotalBytes": 104_857_600,
    "maxPages": 1000,
    "maxOutputs": 100,
    "maxPixelsPerImage": None,
    "maxPixelsPerPage": None,
    "maxTotalPixels": None,
    "maxEstimatedMemoryBytes": 1_342_177_280,
    "maxExecutionSeconds": 180,
    "maxZipBytes": 209_715_200,
    "maxResultBytes": 536_870_912,
}

JPG_TO_PDF_LIMITS = {
    "maxFiles": 50,
    "maxFileBytes": 20_971_520,
    "maxTotalBytes": 209_715_200,
    "maxPages": None,
    "maxOutputs": 1,
    "maxPixelsPerImage": 20_000_000,
    "maxPixelsPerPage": None,
    "maxTotalPixels": 100_000_000,
    "maxEstimatedMemoryBytes": 1_610_612_736,
    "maxExecutionSeconds": 180,
    "maxZipBytes": None,
    "maxResultBytes": 536_870_912,
}

PDF_TO_JPG_LIMITS = {
    "maxFiles": 1,
    "maxFileBytes": 104_857_600,
    "maxTotalBytes": 104_857_600,
    "maxPages": 200,
    "maxOutputs": 200,
    "maxPixelsPerImage": None,
    "maxPixelsPerPage": 16_000_000,
    "maxTotalPixels": None,
    "maxEstimatedMemoryBytes": 805_306_368,
    "maxExecutionSeconds": 300,
    "maxZipBytes": 268_435_456,
    "maxResultBytes": 536_870_912,
}

EXPECTED_TOOLS = {
    "compress-pdf": COMPRESS_PDF_LIMITS,
    "merge-pdf": MERGE_PDF_LIMITS,
    "split-pdf": SPLIT_PDF_LIMITS,
    "jpg-to-pdf": JPG_TO_PDF_LIMITS,
    "pdf-to-jpg": PDF_TO_JPG_LIMITS,
}

EXPECTED_GLOBAL = {
    "retentionSeconds": 3600,
    "maxWaitSeconds": 900,
    "maxQueueLength": 2000,
    "maxConcurrentPerOrigin": 4,
    "defaultTimeoutSeconds": 180,
}

# --- approved failure-code vocabulary (closed; C2 brief, DEC-165) ---

EXPECTED_FAILURE_CODES = [
    ("empty", "error.badRequest", False),
    ("type_mismatch", "error.unsupportedMediaType", False),
    ("size_exceeded", "error.payloadTooLarge", False),
    ("corrupt", "error.badRequest", False),
    ("resource_exceeded", "error.invalidRequest", False),
    ("too_many_files", "error.invalidRequest", False),
    ("total_too_large", "error.payloadTooLarge", False),
    ("too_many_pages", "error.invalidRequest", False),
    ("too_many_pixels", "error.invalidRequest", False),
    ("too_many_outputs", "error.invalidRequest", False),
    ("estimated_memory_exceeded", "error.invalidRequest", False),
    ("zip_too_large", "error.payloadTooLarge", False),
    ("result_too_large", "error.payloadTooLarge", False),
    ("queue_full", "error.rateLimited", True),
    ("max_wait_exceeded", "error.rateLimited", True),
    ("too_many_concurrent", "error.rateLimited", True),
    ("rate_limited", "error.rateLimited", True),
    ("not_found", "error.notFound", False),
    ("expired", "error.notFound", False),
]

ENVELOPE_MESSAGE_KEYS = frozenset(
    {
        "error.badRequest",
        "error.unsupportedMediaType",
        "error.payloadTooLarge",
        "error.invalidRequest",
        "error.rateLimited",
        "error.notFound",
    }
)

#: Private internals that must never appear in the contract or its schema.
FORBIDDEN_CONTRACT_TERMS = (
    "redis",
    "r2_",
    "bucket",
    "account_id",
    "access_key",
    "secret",
    "password",
    "endpoint",
    "allowed_origins",
    "worker",
    "env",
    "token",
    "signed_url",
    "object_key",
)

TOOL_ID_VALUES = ["compress-pdf", "merge-pdf", "split-pdf", "jpg-to-pdf", "pdf-to-jpg"]


def _router_app() -> FastAPI:
    """A bare app carrying only the BE-08 router (wiring-owner pattern)."""
    instance = FastAPI()
    instance.include_router(router)
    return instance


def _factory_app() -> FastAPI:
    """The factory app: the capabilities router is mounted by main.py."""
    return create_app()


def _pdf_bytes(page_count: int = 2) -> bytes:
    buffer = io.BytesIO()
    pdf = pikepdf.Pdf.new()
    for _ in range(page_count):
        pdf.add_blank_page(page_size=(100, 100))
    pdf.save(buffer)
    pdf.close()
    return buffer.getvalue()


def _image_bytes(fmt: str, size: tuple[int, int] = (8, 6)) -> bytes:
    buffer = io.BytesIO()
    Image.new("RGB", size, (200, 30, 40)).save(buffer, format=fmt)
    return buffer.getvalue()


# --- canonical tool registry: R-03 table verbatim ---


def test_tool_ids_are_the_closed_canonical_set() -> None:
    assert [tool.value for tool in ToolId] == TOOL_ID_VALUES
    assert len(ToolId) == 5


def test_registry_entries_are_typed() -> None:
    assert all(isinstance(limits, ToolLimits) for limits in TOOL_LIMITS.values())
    assert isinstance(GLOBAL_LIMITS, GlobalLimits)
    assert all(isinstance(entry, FailureCodeEntry) for entry in FAILURE_CODES)


def test_compress_pdf_limits_match_approved_r03_verbatim() -> None:
    assert TOOL_LIMITS[ToolId.COMPRESS_PDF].model_dump(by_alias=True, mode="json") == (
        COMPRESS_PDF_LIMITS
    )


def test_merge_pdf_limits_match_approved_r03_verbatim() -> None:
    assert TOOL_LIMITS[ToolId.MERGE_PDF].model_dump(by_alias=True, mode="json") == MERGE_PDF_LIMITS


def test_split_pdf_limits_match_approved_r03_verbatim() -> None:
    assert TOOL_LIMITS[ToolId.SPLIT_PDF].model_dump(by_alias=True, mode="json") == SPLIT_PDF_LIMITS


def test_jpg_to_pdf_limits_match_approved_r03_verbatim() -> None:
    assert (
        TOOL_LIMITS[ToolId.JPG_TO_PDF].model_dump(by_alias=True, mode="json") == JPG_TO_PDF_LIMITS
    )


def test_pdf_to_jpg_limits_match_approved_r03_verbatim() -> None:
    assert (
        TOOL_LIMITS[ToolId.PDF_TO_JPG].model_dump(by_alias=True, mode="json") == PDF_TO_JPG_LIMITS
    )


def test_na_axes_are_none_only_where_approved() -> None:
    assert TOOL_LIMITS[ToolId.SPLIT_PDF].max_pixels_per_image is None
    assert TOOL_LIMITS[ToolId.SPLIT_PDF].max_pixels_per_page is None
    assert TOOL_LIMITS[ToolId.SPLIT_PDF].max_total_pixels is None
    assert TOOL_LIMITS[ToolId.JPG_TO_PDF].max_pages is None
    assert TOOL_LIMITS[ToolId.JPG_TO_PDF].max_pixels_per_page is None
    assert TOOL_LIMITS[ToolId.JPG_TO_PDF].max_zip_bytes is None
    assert TOOL_LIMITS[ToolId.PDF_TO_JPG].max_pixels_per_image is None
    assert TOOL_LIMITS[ToolId.PDF_TO_JPG].max_total_pixels is None
    assert TOOL_LIMITS[ToolId.COMPRESS_PDF].max_pixels_per_image is None
    assert TOOL_LIMITS[ToolId.COMPRESS_PDF].max_zip_bytes is None
    assert TOOL_LIMITS[ToolId.MERGE_PDF].max_zip_bytes is None


def test_global_limits_match_approved_r03_verbatim() -> None:
    assert GLOBAL_LIMITS.model_dump(by_alias=True, mode="json") == EXPECTED_GLOBAL


def test_contract_version_is_locked() -> None:
    assert CONTRACT_VERSION == 1
    assert capabilities_payload().version == 1


def test_global_limits_match_settings_defaults_no_drift() -> None:
    assert GLOBAL_LIMITS.retention_seconds == DEFAULT_RETENTION_SECONDS
    assert GLOBAL_LIMITS.max_wait_seconds == DEFAULT_MAX_WAIT_SECONDS
    assert GLOBAL_LIMITS.max_queue_length == DEFAULT_MAX_QUEUE_LENGTH
    assert GLOBAL_LIMITS.max_concurrent_per_origin == DEFAULT_MAX_CONCURRENT_PER_ORIGIN
    assert GLOBAL_LIMITS.default_timeout_seconds == DEFAULT_TIMEOUT_SECONDS


def test_pdf_limits_consistent_with_be02_validation_defaults() -> None:
    assert TOOL_LIMITS[ToolId.COMPRESS_PDF].max_file_bytes == DEFAULT_MAX_PDF_SIZE_BYTES
    assert TOOL_LIMITS[ToolId.COMPRESS_PDF].max_pages == DEFAULT_MAX_PDF_PAGES
    assert TOOL_LIMITS[ToolId.MERGE_PDF].max_file_bytes == DEFAULT_MAX_PDF_SIZE_BYTES
    assert TOOL_LIMITS[ToolId.SPLIT_PDF].max_file_bytes == DEFAULT_MAX_PDF_SIZE_BYTES
    assert TOOL_LIMITS[ToolId.PDF_TO_JPG].max_file_bytes == DEFAULT_MAX_PDF_SIZE_BYTES


def test_image_limits_consistent_with_be02_validation_defaults() -> None:
    assert TOOL_LIMITS[ToolId.JPG_TO_PDF].max_file_bytes == DEFAULT_MAX_IMAGE_SIZE_BYTES
    assert TOOL_LIMITS[ToolId.JPG_TO_PDF].max_pixels_per_image == DEFAULT_MAX_IMAGE_PIXELS


# --- immutability: no mutable global state ---


def test_registry_mapping_is_immutable() -> None:
    with pytest.raises(TypeError):
        TOOL_LIMITS[ToolId.COMPRESS_PDF] = TOOL_LIMITS[ToolId.MERGE_PDF]  # type: ignore[index]
    with pytest.raises(TypeError):
        del TOOL_LIMITS[ToolId.COMPRESS_PDF]  # type: ignore[attr-defined]


def test_tool_limits_instances_are_frozen() -> None:
    with pytest.raises(ValidationError):
        TOOL_LIMITS[ToolId.COMPRESS_PDF].max_files = 99


def test_global_limits_is_frozen() -> None:
    with pytest.raises(ValidationError):
        GLOBAL_LIMITS.retention_seconds = 99


def test_payload_is_fresh_per_call() -> None:
    first = capabilities_payload()
    second = capabilities_payload()
    assert first is not second
    assert first.model_dump(mode="json") == second.model_dump(mode="json")


# --- closed failure-code vocabulary ---


def test_failure_code_vocabulary_is_closed_and_stable() -> None:
    assert [code.value for code in FailureCode] == [item[0] for item in EXPECTED_FAILURE_CODES]


@pytest.mark.parametrize(
    ("code", "message_key", "retryable"),
    EXPECTED_FAILURE_CODES,
    ids=[item[0] for item in EXPECTED_FAILURE_CODES],
)
def test_failure_code_metadata_locked(code: str, message_key: str, retryable: bool) -> None:
    meta = failure_code_meta(FailureCode(code))
    assert isinstance(meta, FailureCodeMeta)
    assert meta.message_key == message_key
    assert meta.retryable is retryable


def test_failure_code_entries_are_frozen() -> None:
    entry = FAILURE_CODES[0]
    assert isinstance(entry, FailureCodeEntry)
    with pytest.raises(ValidationError):
        entry.retryable = True


def test_failure_code_meta_rejects_unknown_codes() -> None:
    with pytest.raises(ValueError, match="unknown failure code"):
        failure_code_meta("not_a_code")  # type: ignore[arg-type]


def test_validation_failure_mapping_is_exact() -> None:
    assert failure_code_for(ValidationFailure.EMPTY) is FailureCode.EMPTY
    assert failure_code_for(ValidationFailure.TYPE_MISMATCH) is FailureCode.TYPE_MISMATCH
    assert failure_code_for(ValidationFailure.SIZE_EXCEEDED) is FailureCode.SIZE_EXCEEDED
    assert failure_code_for(ValidationFailure.CORRUPT) is FailureCode.CORRUPT
    assert failure_code_for(ValidationFailure.RESOURCE_EXCEEDED) is FailureCode.RESOURCE_EXCEEDED


def test_failure_code_for_rejects_unknown_input() -> None:
    with pytest.raises(ValueError, match="unknown validation failure"):
        failure_code_for("empty")  # type: ignore[arg-type]


def test_message_keys_stay_within_existing_envelope_vocabulary() -> None:
    for entry in FAILURE_CODES:
        assert entry.message_key in ENVELOPE_MESSAGE_KEYS
    for code in FailureCode:
        assert failure_code_meta(code).message_key in ENVELOPE_MESSAGE_KEYS


def test_vocabulary_entries_match_enum_metadata() -> None:
    assert len(FAILURE_CODES) == len(FailureCode)
    for entry, code in zip(FAILURE_CODES, FailureCode, strict=True):
        assert entry.code == code.value
        meta = failure_code_meta(code)
        assert entry.message_key == meta.message_key
        assert entry.retryable is meta.retryable


# --- violating upload -> matching machine-readable code ---


def test_violating_upload_empty_bytes_maps_to_matching_code() -> None:
    with pytest.raises(ValidationRejection) as caught:
        validate_pdf(b"")
    assert failure_code_for(caught.value.failure) is FailureCode.EMPTY
    assert caught.value.message_key == "error.badRequest"


def test_violating_upload_oversized_image_maps_to_matching_code() -> None:
    oversized = _image_bytes("JPEG") + b"\x00" * (TOOL_LIMITS[ToolId.JPG_TO_PDF].max_file_bytes + 1)
    with pytest.raises(ValidationRejection) as caught:
        validate_image(
            oversized,
            max_size_bytes=TOOL_LIMITS[ToolId.JPG_TO_PDF].max_file_bytes,
        )
    assert caught.value.failure is ValidationFailure.SIZE_EXCEEDED
    assert failure_code_for(caught.value.failure) is FailureCode.SIZE_EXCEEDED
    assert caught.value.message_key == "error.payloadTooLarge"


def test_violating_upload_too_many_pages_maps_to_matching_code() -> None:
    many_pages = _pdf_bytes(1001)
    max_pages = TOOL_LIMITS[ToolId.COMPRESS_PDF].max_pages
    assert max_pages is not None
    with pytest.raises(ValidationRejection) as caught:
        validate_pdf(many_pages, max_pages=max_pages)
    assert caught.value.failure is ValidationFailure.RESOURCE_EXCEEDED
    assert failure_code_for(caught.value.failure) is FailureCode.RESOURCE_EXCEEDED
    assert caught.value.message_key == "error.invalidRequest"


def test_violating_upload_corrupt_pdf_maps_to_matching_code() -> None:
    corrupt = b"%PDF-1.4\nnot a real pdf body"
    with pytest.raises(ValidationRejection) as caught:
        validate_pdf(corrupt)
    assert caught.value.failure is ValidationFailure.CORRUPT
    assert failure_code_for(caught.value.failure) is FailureCode.CORRUPT
    assert caught.value.message_key == "error.badRequest"


def test_all_mapped_codes_are_advertised_in_the_contract() -> None:
    advertised = {entry.code for entry in FAILURE_CODES}
    for failure in ValidationFailure:
        assert failure_code_for(failure).value in advertised


# --- versioned endpoint ---


def test_capabilities_endpoint_returns_full_approved_contract() -> None:
    response = TestClient(_router_app()).get("/api/v1/capabilities")
    assert response.status_code == 200
    assert response.json() == {
        "version": 1,
        "tools": EXPECTED_TOOLS,
        "global": EXPECTED_GLOBAL,
        "failureCodes": [
            {"code": code, "messageKey": key, "retryable": retryable}
            for code, key, retryable in EXPECTED_FAILURE_CODES
        ],
    }


def test_capabilities_endpoint_tools_order_is_enum_order() -> None:
    body = TestClient(_router_app()).get("/api/v1/capabilities").json()
    assert list(body["tools"]) == TOOL_ID_VALUES


def test_capabilities_endpoint_is_cacheable() -> None:
    response = TestClient(_router_app()).get("/api/v1/capabilities")
    assert response.headers["cache-control"] == CACHE_CONTROL
    assert response.headers["cache-control"] == "public, max-age=3600"


def test_capabilities_endpoint_is_deterministic_across_requests() -> None:
    client = TestClient(_router_app())
    first = client.get("/api/v1/capabilities").text
    second = client.get("/api/v1/capabilities").text
    assert first == second


def test_capabilities_payload_without_settings_uses_canonical_defaults() -> None:
    overridden = dataclasses.replace(
        Settings.from_env(),
        retention_seconds=99,
        max_wait_seconds=7,
        max_queue_length=3,
        max_concurrent_per_origin=1,
        default_timeout_seconds=5,
    )
    assert overridden != Settings.from_env()
    # No settings supplied: the payload falls back to the approved canonical
    # defaults, independent of any environment overrides.
    payload = capabilities_payload()
    assert payload.global_limits.model_dump(by_alias=True, mode="json") == EXPECTED_GLOBAL


def test_capabilities_endpoint_mounted_on_factory_app() -> None:
    response = TestClient(create_app()).get("/api/v1/capabilities")
    assert response.status_code == 200
    assert response.json()["version"] == 1


def test_router_exposes_only_the_capabilities_get_route() -> None:
    assert len(router.routes) == 1
    route = router.routes[0]
    assert isinstance(route, APIRoute)
    assert route.path == "/api/v1/capabilities"
    assert route.methods == {"GET"}


def test_capabilities_endpoint_composes_with_factory_middleware() -> None:
    client = TestClient(_factory_app())
    response = client.get("/api/v1/capabilities")
    assert response.status_code == 200
    assert response.headers["x-request-id"]
    assert response.json()["version"] == 1


def test_capabilities_response_leaks_no_private_internals() -> None:
    body = TestClient(_router_app()).get("/api/v1/capabilities").text.lower()
    for term in FORBIDDEN_CONTRACT_TERMS:
        assert term not in body


# --- OpenAPI determinism and safety ---


def test_openapi_paths_are_deterministic_and_locked() -> None:
    openapi = _router_app().openapi()
    assert list(openapi["paths"]) == ["/api/v1/capabilities"]
    operation = openapi["paths"]["/api/v1/capabilities"]["get"]
    assert operation["operationId"] == "get_capabilities_api_v1_capabilities_get"
    assert operation["tags"] == ["capabilities"]
    assert operation["summary"] == "Capability and limits contract"
    assert list(operation["responses"]) == ["200"]
    assert operation["responses"]["200"] == {
        "description": "Successful Response",
        "content": {
            "application/json": {"schema": {"$ref": "#/components/schemas/CapabilitiesResponse"}}
        },
    }


def test_openapi_tool_limits_schema_locked() -> None:
    schema = _router_app().openapi()["components"]["schemas"]["ToolLimits"]
    assert schema["type"] == "object"
    assert schema["additionalProperties"] is False
    assert list(schema["properties"]) == [
        "maxFiles",
        "maxFileBytes",
        "maxTotalBytes",
        "maxPages",
        "maxOutputs",
        "maxPixelsPerImage",
        "maxPixelsPerPage",
        "maxTotalPixels",
        "maxEstimatedMemoryBytes",
        "maxExecutionSeconds",
        "maxZipBytes",
        "maxResultBytes",
    ]
    assert schema["required"] == list(schema["properties"])
    assert schema["properties"]["maxPages"]["anyOf"] == [
        {"type": "integer"},
        {"type": "null"},
    ]


def test_openapi_global_limits_schema_locked() -> None:
    schema = _router_app().openapi()["components"]["schemas"]["GlobalLimits"]
    assert schema["type"] == "object"
    assert schema["additionalProperties"] is False
    assert list(schema["properties"]) == [
        "retentionSeconds",
        "maxWaitSeconds",
        "maxQueueLength",
        "maxConcurrentPerOrigin",
        "defaultTimeoutSeconds",
    ]
    assert schema["required"] == list(schema["properties"])


def test_openapi_failure_code_entry_schema_locked() -> None:
    schema = _router_app().openapi()["components"]["schemas"]["FailureCodeEntry"]
    assert schema["type"] == "object"
    assert schema["additionalProperties"] is False
    assert list(schema["properties"]) == ["code", "messageKey", "retryable"]
    assert schema["required"] == ["code", "messageKey", "retryable"]
    assert schema["properties"]["retryable"]["type"] == "boolean"


def test_openapi_response_schema_locked() -> None:
    schema = _router_app().openapi()["components"]["schemas"]["CapabilitiesResponse"]
    assert schema["type"] == "object"
    assert schema["additionalProperties"] is False
    assert list(schema["properties"]) == ["version", "tools", "global", "failureCodes"]
    assert schema["required"] == ["version", "tools", "global", "failureCodes"]
    assert schema["properties"]["tools"]["type"] == "object"
    assert schema["properties"]["tools"]["additionalProperties"] == {
        "$ref": "#/components/schemas/ToolLimits"
    }


def test_openapi_leaks_no_private_internals() -> None:
    serialized = json.dumps(_router_app().openapi()).lower()
    for term in FORBIDDEN_CONTRACT_TERMS:
        assert term not in serialized


def test_openapi_schema_is_deterministic_across_app_instances() -> None:
    assert _router_app().openapi() == _router_app().openapi()


def test_response_model_rejects_unknown_fields() -> None:
    with pytest.raises(ValidationError):
        CapabilitiesResponse.model_validate(
            {
                "version": 1,
                "tools": EXPECTED_TOOLS,
                "global": EXPECTED_GLOBAL,
                "failureCodes": [
                    {"code": c, "messageKey": k, "retryable": r}
                    for c, k, r in EXPECTED_FAILURE_CODES
                ],
                "extraField": True,
            }
        )
