#!/usr/bin/env python3
"""Verify committed hostile PDF fixtures match expected SHA256 hashes.

This is the sole authoritative integrity mechanism for U-FIXTURES.

CANONICAL BYTES STRATEGY:
The hostile PDF fixtures are committed as static binary files because pikepdf
(and qpdf) generate non-deterministic output across runs (random IVs, trailer
IDs, timestamps). Per phase-5-remediation-plan-v2.md:

  "Each generated by a committed deterministic generator script OR committed
   bytes with recorded hashes"

These fixtures use the second option: committed bytes + recorded SHA256 hashes.
The hashes below pin the exact expected bytes; this script verifies them.
"""

import hashlib
import sys
from pathlib import Path

_FIXTURE_HASHES = {
    "js_auto_launch.pdf": "a29b9f6dc9cd1ffc3258b4873f95d171e11cc8fc49bc1b8dcd8774c540f6b33e",
    "embedded_attachment.pdf": "40b32b232bff384e9b96c2598f9b30967e18be6014b8796e840d3a1b3af75652",
    "openaction_launch.pdf": "881dd83c01d40bec1075c6b5365daf352b43eff7bf45973424348863a7442908",
    "encrypted_protected.pdf": "f672bd3bb2cdbe6498f87f800283e3095660b0a1c87e05284851d7a0e925c3a5",
    "corrupt_structure.pdf": "102243890ddd86c465f70549a40252643564f94783d744b25eeb970d266c9f16",
    "benign_control.pdf": "070624b0807f199945362e54fe5fd67d9fdff56f3b49cee45ebaf36dd2756e40",
}


def main() -> int:
    output_dir = Path(__file__).parent / "fixtures" / "hostile"

    print("=" * 70)
    print("FIXTURE COMMIT VERIFICATION")
    print("=" * 70)
    print(f"Fixture directory: {output_dir}")
    print()

    all_match = True

    for filename, expected_hash in _FIXTURE_HASHES.items():
        filepath = output_dir / filename

        if not filepath.exists():
            print(f"✗ {filename}: FILE MISSING")
            all_match = False
            continue

        actual_hash = hashlib.sha256(filepath.read_bytes()).hexdigest()

        if actual_hash == expected_hash:
            print(f"✓ {filename}: {actual_hash[:32]}... MATCHES COMMITTED HASH")
        else:
            print(f"✗ {filename}: MISMATCH!")
            print(f"  Expected: {expected_hash}")
            print(f"  Actual:   {actual_hash}")
            all_match = False

    print("=" * 70)
    if all_match:
        print("RESULT: All fixtures match committed hashes - VERIFIED")
        return 0
    else:
        print("RESULT: FIXTURE VERIFICATION FAILED")
        return 1


if __name__ == "__main__":
    sys.exit(main())
